const objToString = (obj) => {
    if(obj){
        const objInfo = obj[keys.objInfo];
        return objInfo? `Obj: ${objInfo.s+1}-${objInfo.e+1}, ${objInfo.k}` : "Obj: No Info";
    }
    return "Obj: Null";
};
const newPreDiff = (jObject, subject) => {
    const parseObj = (parent) => {
        // initialize range for the other object, set to -1 to indicate not found
        // check for null because added list braces do not have objInfo
        if(parent[keys.objInfo]){
            const objInfo = parent[keys.objInfo];
            objInfo.t = oTypes.startObj;   // indicates an object start
            objInfo.i = objInfo.s;  // make compatible with valInfo
            objInfo.iOther = -1;
            objInfo.eOther = -1;
            objInfo.keyMatch = false;
            objInfo.valMatch = false;
            objInfo.subject = subject;
        }

        const valInfo = parent[keys.valInfo];
        //console.log("parseObj")
        
        for(let infoItem of valInfo){
            // initialize line number for the other object, set to -1 to indicate not found
            infoItem.iOther = -1;
            infoItem.keyMatch = false;
            infoItem.valMatch = false;
            infoItem.subject = subject;

            const key = infoItem.k;
            const child = parent[key];

            if(getType(child) === cType.o){
                //console.log(">>", key, objToString(parent), "\n  ", objToString(child))
                parseObj(child);
            }
        }
    }

    parseObj(jObject);
}

const newObjDiff = (objL, objR) => {
    const matchObjects = (left, right) => {
        if(left && right){
            const objInfoL = left[keys.objInfo];
            const objInfoR = right[keys.objInfo];

            // ignore added list braces, which do not have objInfo
            if(!objInfoL && !objInfoR){
                //console.log("added list braces match")
                return true;
            }

            // since we're parsing it, call keyMatch true
            objInfoL.keyMatch = true;
            objInfoR.keyMatch = true;

            const valMatch = (objInfoL?.k === objInfoR?.k);
            //console.log(objInfoL?.k, valMatch, objInfoR?.k)
            if(
                valMatch &&        // if unmatched, leave false, -1, -1
                !objInfoL.valMatch // skip this part if already set
            ){
                objInfoL.valMatch = true;
                objInfoR.valMatch = true;
    
                objInfoL.iOther = objInfoR.i;
                objInfoL.eOther = objInfoR.e;

                objInfoR.iOther = objInfoL.i;
                objInfoR.eOther = objInfoL.e;
                //console.log("Obj Equal", objInfoL.subject)
                //console.log(">>", objToString(left), "\n  ", objToString(right))
            }
            
            return valMatch;
        }
    }

    const parseObj = (parentL, parentR) => {
        if(matchObjects(parentL, parentR)){
            const valInfoL = parentL[keys.valInfo];
           
            for(let infoItemL of valInfoL){
                const key = infoItemL.k;
                const childL = parentL[key];
                const childR = parentR[key];

                const cTypeL = getType(childL);
                const cTypeR = getType(childR);

                if(
                    !Util.isNull(childL) && 
                    !Util.isNull(childR) && 
                    cTypeL === cTypeR
                ){
                    // find the corresponding info item in the other object
                    const infoItemR = parentR[keys.valInfo].find(t => t.k === infoItemL.k);

                    if(infoItemR){
                        infoItemL.iOther = infoItemR.i;
                        infoItemR.iOther = infoItemL.i;

                        infoItemL.keyMatch = true;
                        infoItemR.keyMatch = true;

                        let valMatch;

                        //console.log(`${infoItemL.i + 1}: keyMatch: ${infoItemL.k}`);

                        if(cTypeL === cType.o){
                            valMatch = parseObj(childL, childR);
                            infoItemL.valMatch = valMatch;
                            infoItemR.valMatch = valMatch;
                        }
                        else {
                            valMatch = (childL === childR);

                            infoItemL.valMatch = valMatch;
                            infoItemR.valMatch = valMatch;
                            if(valMatch){
                                //console.log(`${infoItemL.i + 1}: valMatch: ${infoItemL.k}: '${childL}', ${childR}'`);
                            }
                        }
                    }
                    else {
                        // should never happen in unmodified data generated by this app
                        console.error(`${infoItemL.i + 1}: Json improperly formed in file opposite ${infoItemL.k}, line ${infoItemL.i + 1}`);
                    }

                }
                else{
                    //console.log(`${infoItemL.i + 1}: No match: ${key} => '${childL}' '${childR}'`)
                }
            }

            return true;
        }

        return false;
    }

    const init = () => {
        //console.log("Diff LR")
        parseObj(objL, objR);
        //console.log("Diff RL")
        parseObj(objR, objL);
    }
    init();
}

const newResultParse = (objL, objR) => {
    const genUq = (valInfo, subject) => {
        return (subject === LEFT) ? 
            `${valInfo.k}${valInfo.i}_${valInfo.iOther}` : 
            `${valInfo.k}${valInfo.iOther}_${valInfo.i}`;
    }

    const newResultAcc = () => {
        const set = new Set();
        const list = [];

        const add = (valInfo, subject) => {
            if(valInfo){
                const uq = genUq(valInfo, subject);
                //console.log(subject, uq)
                if(!set.has(uq)){
                    //console.log(subject, valInfo.k, valInfo.t, !!valInfo.keyMatch, !!valInfo.valMatch, valInfo.i, valInfo.iOther)
                    set.add(uq);
                    list.push(valInfo)
                }
            }
        }

        const sort = () => list.sort((a, b) => a.i - b.i);

        return {
            add: add,
            sort: sort,
            toList: () =>  list
        };
    }

    let tab = 0;

    const preParse = (parent, grandparent) => {
        if(parent[keys.objInfo] && grandparent && !grandparent[keys.objInfo]){
            grandparent[keys.objInfo] = {...parent[keys.objInfo], k: "ignore"};
            console.log("added", grandparent[keys.objInfo])
        }

        const valInfo = parent[keys.valInfo];
        
        for(let infoItem of valInfo){
            const child = parent[infoItem.k];
            if(getType(child) === cType.o){
                preParse(child, parent);
            }
        }
    }

    const accResults = (parents) => {
        //console.log("s tab", tab++);
        const parentAcc = newResultAcc();
        const valInfoAcc = newResultAcc();
        parents.forEach((p) => {
            if(p){
                const objInfo = p[keys.objInfo];
                objInfo.rAcc = parentAcc;
                objInfo.tab = tab;

                const vInfo = p[keys.valInfo];
                vInfo.forEach(v => parentAcc.add(v, v.subject))
            }
        });

        tab++
        
        parentAcc.toList().forEach(info => {
            if(info.t === tTypes.oBrace){
                const key = info.k;
                //console.log(parents.map((p) => (p && p[key])? p[key][keys.objInfo]?.k : null))
                accResults(
                    parents.map((p) => p? p[key] : null)
                );
            }
        });

        tab--;
        
        //endObjAcc.toList().forEach(info => disp(info));
        //console.log("e tab", --tab);
    }

    let resultAcc;

    const listResults = (parents) => {
        let parentAcc;
        parents.forEach((p) => {
            if(p){
                const objInfo = p[keys.objInfo];
                resultAcc.add(objInfo, objInfo.subject);

                parentAcc = objInfo.rAcc;
            }
        });
        
        parentAcc.toList().forEach(info => {
            if(info.t === tTypes.oBrace){
                const key = info.k;
                //console.log(parents.map((p) => (p && p[key])? p[key][keys.objInfo]?.k : null))
                listResults(
                    parents.map((p) => p? p[key] : null)
                );
            }
        });
        
        //endObjAcc.toList().forEach(info => disp(info));
    }

    const disp = (r, parentTab = 0) => {
        if(r){
            const indent = (parentTab)? ' '.repeat(parentTab * 2) : "";
            const keyMatch = r.keyMatch? "Key" : "---";
            const valMatch = r.valMatch? "Val" : "---";
            const i = r.i;
            const iOther = r.iOther;
            console.log(`${keyMatch}${valMatch}: ${indent} ${r.t} ${r.k} ${SubjectNames[r.subject]} ${i + 1}, ${iOther + 1}`);

        }
    }
    const init = () => {
        resultAcc = newResultAcc();

        if(objL[keys.objInfo]?.valMatch){
            //subject = LEFT;
            preParse(objL, null);
            preParse(objR, null);
            console.log("\nResults")
            accResults([objL, objR]);
            listResults([objL, objR]);

            resultAcc.sort();
            const list = resultAcc.toList();
            for(let parent of list){
                disp(parent, parent.tab)
                parent.rAcc.sort();
                const childList = parent.rAcc.toList();
                for(let r of childList){
                    disp(r, parent.tab + 1);
                }

                const cBrace = {...parent, t: oTypes.endObj, i: parent.e, iOther: parent.eOther};
                disp(cBrace, parent.tab)
            }


            //dispResults();
            // console.log(results);
        }
    }
    init();
}

const ObjDiffMain = (() => {
    const init = (objL, objR) => {
        newPreDiff(objL, LEFT);
        newPreDiff(objR, RIGHT);

        newObjDiff(objL, objR);

        const resultParse = newResultParse(objL, objR);
    };

    return {
        init: (left, right) => init(left, right)
    };
})();