const objToString = (obj) => {
    if(obj){
        const objInfo = obj[keys.objInfo];
        return objInfo? `Obj: ${objInfo.range.iStart+1}-${objInfo.range.iEnd+1}, ${objInfo.iClass}` : "Obj: No Info";
    }
    return "Obj: Null";
};
const newPreDiff = (jObject) => {
    const parseObj = (parent, subject) => {
        // initialize range for the other object, set to -1 to indicate not found
        // check for null because added list braces do not have objInfo
        if(parent[keys.objInfo]){
            const objInfo = parent[keys.objInfo];
            objInfo.rangeOther = {iStart: -1, iEnd: -1};
            objInfo.match = false;
            objInfo.subject = subject;
        }

        const valInfo = parent[keys.valInfo];
        //console.log("parseObj")
        
        for(let infoItem of valInfo){
            // initialize line number for the other object, set to -1 to indicate not found
            infoItem.iOther = -1;
            infoItem.keyMatch = false;
            infoItem.valMatch = false;
            infoItem.subject = subject;

            const key = infoItem.k;
            const child = parent[key];

            if(getType(child) === cType.o){
                //console.log(">>", key, objToString(parent), "\n  ", objToString(child))
                parseObj(child);
            }
        }
    }

    parseObj(jObject);
}

const newObjDiff = (objL, objR) => {
    let results = [];

    const matchObjects = (left, right) => {
        if(left && right){
            // handle added list braces, which do not have objInfo
            if(!left[keys.objInfo] && !right[keys.objInfo]){
                console.log("added list braces match")
                return true;
            }

            const objInfoL = left[keys.objInfo];
            const objInfoR = right[keys.objInfo];

            const match = (objInfoL?.iClass === objInfoR?.iClass);
    
            if(match && !objInfoL.match){// skip this part if already set
                objInfoL.match = true;
                objInfoR.match = true;
    
                objInfoL.rangeOther = {...objInfoR.range};
                objInfoR.rangeOther = {...objInfoL.range};
                console.log("Obj Equal")
                console.log(">>", objToString(left), "\n  ", objToString(right))
            }
            
            return match;
        }
    }

    const parseObj = (parentL, parentR) => {
        if(matchObjects(parentL, parentR)){
            const valInfoL = parentL[keys.valInfo];
           
            for(let infoItemL of valInfoL){
                const key = infoItemL.k;
                const childL = parentL[key];
                const childR = parentR[key];

                const cTypeL = getType(childL);
                const cTypeR = getType(childR);

                if(childL && childR && cTypeL === cTypeR){
                    // find the corresponding info item in the other object
                    const infoItemR = parentR[keys.valInfo].find(t => t.k === infoItemL.k);

                    if(infoItemR){
                        infoItemL.iOther = infoItemR.i;
                        infoItemR.iOther = infoItemL.i;

                        infoItemL.keyMatch = true;
                        infoItemR.keyMatch = true;

                        console.log(`${infoItemL.i + 1}: keyMatch: ${infoItemL.k}`);

                        if(cTypeL === cType.o){
                            parseObj(childL, childR);
                        }
                        else if(!infoItemL.valMatch){
                            const valMatch = (childL === childR);

                            infoItemL.valMatch = valMatch;
                            infoItemR.valMatch = valMatch;
                            if(valMatch){
                                console.log(`${infoItemL.i + 1}: valMatch: ${infoItemL.k}: '${childL}', ${childR}'`);
                            }
                        }
                    }
                    else {
                        // should never happen in unmodified data generated by this app
                        console.error(`${infoItemL.i + 1}: Json improperly formed in file opposite ${infoItemL.k}, line ${infoItemL.i + 1}`);
                    }

                }
                else{
                    console.log(`${infoItemL.i + 1}: No match: ${key} => '${childL}' '${childR}'`)
                }
            }
        }
    }

    const parseResults = (parent) => {
        if(parent[keys.objInfo]){
            results.push(parent[keys.objInfo]);
        }

        const valInfo = parent[keys.valInfo];
        
        for(let infoItem of valInfo){
            results.push(infoItem);

            const key = infoItem.k;
            const child = parent[key];

            if(getType(child) === cType.o){
                parseResults(child);
            }
        }
    }

    const dispResults = () => {
        results.sort((a, b) => a.subject - b.subject);
        for(let item of results){
            if(item.range){
                const match = item.match? "obj" : "---";
                console.log(`${match}: ${item.iClass}, ${item.range.iStart + 1}-${item.range.iEnd + 1}, ${item.rangeOther.iStart + 1}-${item.rangeOther.iEnd + 1}`);
            }
            else{
                const keyMatch = item.keyMatch? "Key" : "---";
                const valMatch = item.valMatch? "Val" : "---";
                console.log(`${keyMatch}${valMatch}: ${item.k}, ${item.i + 1}, ${item.iOther + 1}`);
            }
        }
    }

    const init = () => {
        console.log("Diff LR")
        parseObj(objL, objR);
        console.log("Diff RL")
        parseObj(objR, objL);

        console.log("\nResults")
        parseResults(objL);
        parseResults(objR);
        dispResults();
        // console.log(results);
    }
    init();
}

const ObjDiffMain = (() => {
    const init = (objL, objR) => {
        const preDiffL = newPreDiff(objL, LEFT);
        const preDiffR = newPreDiff(objR, RIGHT);

        const objDiff = newObjDiff(objL, objR);
    };

    return {
        init: (left, right) => init(left, right)
    };
})();